# see _data/meta.yml (so you don't have to restart jekyll to see changes)
baseurl:
url: https://tonepaintingindustries.github.io/
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']
collections:
  - resources
  - software
